Repository Finschia/ostracon, pull requests merged in 2021-10, with the labels that each got.

#327 Add libsodium test on Github Actions
  .github/workflows/coverage.yml
  Makefile
  crypto/vrf/keygen_test.go
  crypto/vrf/vrf_libsodium_test.go
  crypto/vrf/vrf_r2ishiguro.go
Labels: C: test

#337 Improve dependabot
  .github/dependabot.yml
Labels: C: enhancement

#336 [Security] Remove unused package-lock.json
  .gitignore
  docs/package-lock.json
Labels: C: bug, P: emergency
