Repository Finschia/ostracon, pull requests merged in 2021-11, with the labels that each got.

#335 Improve composite key Bytes/FromBytes and make tools
  abci/cmd/abci-cli/abci-cli.go
  abci/example/kvstore/helpers.go
  abci/example/kvstore/helpers_test.go
  abci/example/kvstore/kvstore_test.go
  abci/example/kvstore/persistent_kvstore.go
  abci/example/kvstore/tool/make_val_set_change_tx.go
  abci/example/kvstore/tool/make_val_set_change_tx.sh
  cmd/ostracon/main.go
  crypto/bls/bls.go
  crypto/composite/composite.go
  crypto/composite/composite_test.go
  crypto/encoding/codec.go
  privval/file_test.go
  rpc/client/evidence_test.go
  test/maverick/main.go
  types/block.go
Labels: C: enhancement

#340 Modify omission of change to change ValidatorSet to VoterSet
  consensus/state.go
Labels: C: bug, P: emergency

#341 Remove `default` case
  p2p/peer.go
Labels: C: enhancement

#346 Add CODEOWNERS
  .github/CODEOWNERS
Labels: C: enhancement

#345 fix: Modify omission of change to change ValidatorSet to VoterSet for marverick
  CONTRIBUTING.md
  test/maverick/consensus/state.go
Labels: C: bug

#348 Fix version.go (Rollback to only use `OCCoreSemVer`)
  .github/workflows/docker.yml
  .github/workflows/proto-docker.yml
  .goreleaser.yml
  DOCKER/build.sh
  DOCKER/push.sh
  Makefile
  cmd/ostracon/commands/version.go
  cmd/ostracon/commands/version_test.go
  scripts/dist.sh
  tools/tm-signer-harness/Dockerfile
  tools/tm-signer-harness/Makefile
  version/version.go
Labels: C: enhancement
