Repository Finschia/ostracon, pull requests merged in 2022-06, with the labels that each got.

#426 Remove the check if binary is for amd64
  networks/local/localnode/wrapper.sh
Labels: C: enhancement

#429 [Security] Apply runc version 1.1.2
  go.mod
  go.sum
Labels: C: bug, P: emergency

#428 bls-eth-go-binary version update for apple M1 chip
  go.mod
  go.sum
Labels: C: enhancement

#417 Add KMS functionality
  cmd/ostracon/commands/reset_test.go
  cmd/ostracon/commands/show_validator.go
  cmd/ostracon/commands/show_validator_test.go
  cmd/ostracon/main.go
  config/toml.go
  node/node.go
  node/node_test.go
  privval/test_util.go
  privval/test_util_test.go
  test/kms/bench_test.go
Labels: C: enhancement

#432 Clean up unused configuration files
  .github/mergify.yml
  .github/workflows/release.yml
  .goreleaser.yml
  .vscode/settings.json
  CONTRIBUTING.md
  Vagrantfile
Labels: C: enhancement

#433 tag v1.0.6
  CHANGELOG.md
Labels: C: release

#434 Upgrade to golang-1.18
  .github/workflows/abci.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  DOCKER/Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  networks/local/localnode/Dockerfile
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
  tools/proto/Dockerfile
Labels: C: enhancement
