Repository Finschia/ostracon, pull requests merged in 2022-11, with the labels that each got.

#480 tag v1.0.7
  CHANGELOG.md
Labels: C: release

#484 Avoid panic when addr does not exist in book
  p2p/pex/addrbook.go
Labels: C: bug

#487 Add test of IsGood()
  p2p/pex/addrbook_test.go
Labels: C: test

#485 Optimization of function signChallenge()
  p2p/conn/secret_connection.go
Labels: C: enhancement

#490 fix: Move `types/test_util.go:MakeBlock` into `types/block.go`
  types/block.go
  types/test_util.go
Labels: C: bug

#492 Use the value receiver instead of the pointer receiver in Pubkey.Identity()
  crypto/composite/composite.go
Labels: C: enhancement

#493 Validate proof with ECVRF_decode_proof in vrfEd25519r2ishiguro.ProofToHash()
  crypto/vrf/vrf_r2ishiguro.go
  crypto/vrf/vrf_r2ishiguro_test.go
Labels: C: enhancement

#494 Remove sort from proposer's selection algorithm
  libs/rand/sampling.go
Labels: C: enhancement

#496 Add validation at the beginning of func:RandomSamplingWithPriority
  libs/rand/sampling.go
  libs/rand/sampling_test.go
Labels: C: enhancement

#491 fix: Update the dead links
  docs/README.md
  docs/en/01-overview.md
  docs/en/02-consensus.md
  docs/en/03-tx-sharing.md
  docs/ja/02-consensus.md
  docs/ja/03-tx-sharing.md
Labels: C: documentation

#497 fix: Update the http status code handling on upnp
  p2p/upnp/upnp.go
Labels: C: enhancement

#498 fix: fix overriding tx index of duplicated txs
  state/txindex/indexer_service.go
  state/txindex/indexer_service_test.go
Labels: C: bug

#500 fix: return error when AddChannel fails
  node/node.go
  node/node_test.go
  p2p/mocks/node_info.go
  p2p/mocks/peer.go
  p2p/node_info.go
  p2p/transport.go
  p2p/transport_test.go
Labels: C: enhancement

#505 Upgrade golangci-lint to v1.50.1
  .github/workflows/lint.yml
  .golangci.yml
  consensus/byzantine_test.go
  crypto/bls/bls_test.go
  p2p/transport_test.go
Labels: C: enhancement

#504 Fix typo of the function ValidateBasic
  types/block.go
  types/block_test.go
Labels: C: bug

#502 Fix to also remove VoterParams and LastProofHash in PruneStates
  state/mocks/batch.go
  state/mocks/db.go
  state/store.go
  state/store_test.go
Labels: C: bug

#508 Remove unsed the functioin `StateProvider`
  node/node.go
Labels: C: enhancement

#506 Fix so that HTTP request don't wait for responses indefinitely
  cmd/ostracon/commands/debug/util.go
  libs/net/http.go
  libs/net/http_test.go
  p2p/switch_test.go
  p2p/upnp/upnp.go
  rpc/client/rpc_test.go
  rpc/jsonrpc/client/test_util.go
Labels: C: enhancement

#507 fix: return postCheck error to abci client
  abci/types/types.pb.go
  consensus/replay_stubs.go
  mempool/cache_test.go
  mempool/clist_mempool.go
  mempool/clist_mempool_system_test.go
  mempool/clist_mempool_test.go
  mempool/mempool.go
  mempool/mempool_test.go
  mempool/mock/mempool.go
  mempool/reactor_test.go
  node/node.go
  node/node_test.go
  proto/ostracon/abci/types.proto
  rpc/core/mempool.go
  rpc/core/types/responses.go
  state/execution.go
  state/tx_filter.go
  test/maverick/consensus/replay_stubs.go
  test/maverick/node/node.go
Labels: C: enhancement

#509 Fix code duplication in the newHash
  p2p/pex/addrbook.go
Labels: C: enhancement

#510 Add validation of the ValidatorsHash, Round and Proof
  .github/workflows/e2e.yml
  crypto/vrf/README.md
  crypto/vrf/internal/vrf/vrf.go
  crypto/vrf/vrf_coniks.go
  crypto/vrf/vrf_libsodium.go
  crypto/vrf/vrf_r2ishiguro.go
  evidence/pool_test.go
  evidence/verify_test.go
  test/e2e/Makefile
  test/e2e/runner/test.go
  types/block.go
  types/block_test.go
  types/validation.go
Labels: C: enhancement

#511 Update the default value of DefaultMaxTolerableByzantinePercentage
  types/params.go
  types/voter_set.go
  types/voter_set_test.go
Labels: C: enhancement

#512 Update using `GITHUB_OUTPUT` environment
  .github/workflows/docker.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/proto-docker.yml
Labels: C: enhancement
