Repository Finschia/ostracon, pull requests merged in 2023-07, with the labels that each got.

#651 update types/part_set.go
  types/part_set.go
Labels: C: enhancement

#652 Allow ostracon to verify the old r2ishiguro vrf proofs
  crypto/ed25519/ed25519.go
  crypto/ed25519/internal/r2ishiguro/testutil/prove.go
  crypto/ed25519/internal/r2ishiguro/vrf.go
  crypto/ed25519/internal/r2ishiguro/vrf_test.go
  crypto/ed25519/migration.go
  crypto/ed25519/migration_test.go
  go.mod
  go.sum
  state/execution.go
  statesync/stateprovider.go
  types/validation.go
Labels: C: enhancement

#662 Change pathlib version from v1.0.0 to v0.15.0
  go.mod
  go.sum
Labels: dependencies

#665 build: update golang version to 1.20
  .github/workflows/abci.yml
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/lint.yml
  DOCKER/Dockerfile
  Makefile
  README.md
  abci/example/example_test.go
  abci/example/kvstore/helpers_test.go
  cmd/ostracon/commands/show_validator_test.go
  crypto/merkle/proof_key_path_test.go
  go.mod
  go.sum
  libs/log/zerolog_logger_test.go
  libs/rand/random_test.go
  mempool/v0/clist_mempool_system_test.go
  networks/local/localnode/Dockerfile
  privval/file_test.go
  scripts/proto-gen.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
  test/e2e/generator/main_test.go
  test/fuzz/p2p/pex/init-corpus/main.go
  tools/proto/Dockerfile
  types/event_bus_test.go
Labels: C: enhancement

#672 feat: add max_batch_request_num feature
  cmd/ostracon/commands/light.go
  config/config.go
  config/config_test.go
  config/toml.go
  node/node.go
  rpc/jsonrpc/server/common_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_json_handler_test.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_server_test.go
  test/e2e/node/main.go
Labels: C: enhancement, D: good first issue

#679 tag v1.1.1
  CHANGELOG.md
  README.md
Labels: C: release
