Repository Finschia/ostracon, pull requests merged in 2023-03, with the labels that each got.

#578 Add codeowner
  .github/CODEOWNERS
Labels: C: enhancement

#575 Fix TODOs in #546
  abci/example/example_test.go
  blockchain/msgs.go
  blockchain/msgs_test.go
  blockchain/v2/reactor_test.go
  consensus/state_test.go
  light/client_test.go
  privval/signer_endpoint.go
  privval/signer_server.go
  rpc/core/blocks_test.go
  rpc/core/env_test.go
  state/indexer/block/kv/util.go
  state/indexer/sink/psql/psql.go
  state/indexer/sink/psql/psql_test.go
  state/mocks/evidence_pool.go
  state/mocks/store.go
  statesync/syncer_test.go
  test/kms/bench_test.go
  types/block_test.go
  types/protobuf_test.go
Labels: C: enhancement

#567 Add Ostracon specification skeleton
  spec/README.md
  spec/abci/abci.md
  spec/abci/apps.md
  spec/consensus/proposer-selection.md
  spec/core/data_structures.md
  spec/core/state.md
  spec/introduction/overview.md
  spec/p2p/v0.34/configuration.md
  spec/rpc/README.md
  spec/static/oc.svg
  spec/static/tm.svg
Labels: C: documentation

#576 feat: big genesis file
  node/node.go
  node/node_test.go
Labels: C: enhancement

#585 tag v1.0.9
  CHANGELOG.md
Labels: C: release
